#ifndef DINKBOT_VARS_H
#define DINKBOT_VARS_H

extern const int16_t v_L_forward,
        v_R_forward,
        v_L_turn90cw,
        v_R_turn90cw,
        v_L_turn90ccw,
        v_R_turn90ccw,
        v_L_turn10LBack,
        v_R_turn10LBack,
        v_L_turn10RBack,
        v_R_turn10RBack,
        v_L_turn30LBack,
        v_R_turn30LBack,
        v_L_turn30RBack,
        v_R_turn30RBack,
        v_L_turn30LCenter,
        v_R_turn30LCenter,
        v_L_turn30RCenter,
        v_R_turn30RCenter,
        v_L_backUp,
        v_R_backUp,
        v_eject,
        v_lift,
        v_retract,
        v_L_fixPos,
        v_R_fixPos;

extern const uint16_t t_turn90,
        t_backUp,
        t_forward1,
        t_turn10Back,
        t_turn30Back,
        t_turn30Center,
        t_evade,
        t_backUpFix,
        t_smallBackup,
        t_eject,
        t_lift1,
        t_lift2,
        t_retract,
        t_fixPos,
        t_shake,
        t_forward,
        t_forward2,
        t_turn30;
#endif
